app:
  baseUrl: http://localhost:7007

backend:
  baseUrl: http://localhost:7007
  listen: ":7007"
  reading:
    allow:
      - host: ${FORGEJO_URL}

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

auth:
  environment: production
  session:
    secret: ${AUTH_SESSION_SECRET}
  providers:
    oidc:
      production:
        metadataUrl: https://${AUTH_OIDC_URL}/.well-known/openid-configuration
        clientId: ${AUTH_OIDC_CLIENT_ID}
        clientSecret: ${AUTH_OIDC_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: emailMatchingUserEntityProfileEmail

catalog:
  locations:
    - type: file
      target: ./catalog/index.yaml
      rules:
        - allow: [Location, Group, User, System, Domain, Resource]

    - type: file
      target: ./templates/empty/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ./templates/go/service/template.yaml
      rules:
        - allow: [Template]

integrations:
  gitea:
    - host: ${FORGEJO_URL}
      baseUrl: http://${FORGEJO_URL}
      apiBaseUrl: http://${FORGEJO_URL}/api/v1
      username: ${FORGEJO_USERNAME}
      password: ${FORGEJO_TOKEN}

  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
