# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infra
  title: Infrastructure Team
  description: ""
spec:
  type: team
  children: []
