import {
  coreServices,
  createBackendModule,
} from '@backstage/backend-plugin-api';
import { createTemplateAction } from '@backstage/plugin-scaffolder-node';
import { scaffolderActionsExtensionPoint } from '@backstage/plugin-scaffolder-node/alpha';
import {
  ScmIntegrations,
  ScmIntegrationRegistry,
} from '@backstage/integration';
import simpleGit from 'simple-git';
import fs from 'fs-extra';
import path from 'path';

export const scaffolderModuleForgejo = createBackendModule({
  pluginId: 'scaffolder',
  moduleId: 'forgejo',
  register(reg) {
    reg.registerInit({
      deps: {
        logger: coreServices.logger,
        scaffolderActions: scaffolderActionsExtensionPoint,
        config: coreServices.rootConfig,
      },
      async init({ scaffolderActions, logger, config }) {
        logger.info('Starting Forgejo PR plugin!');
        const integrations = ScmIntegrations.fromConfig(config);
        scaffolderActions.addActions(
          createForgejoWriteAction({ integrations }),
        );
      },
    });
  },
});

export function createForgejoWriteAction(options: {
  integrations: ScmIntegrationRegistry;
}) {
  const { integrations } = options;

  return createTemplateAction({
    id: 'forgejo:commit-directory',
    description: 'Renders a workspace directory and commits it to Forgejo.',
    schema: {
      input: {
        host: z => z.string().optional(),
        owner: z => z.string(),
        repo: z => z.string(),
        sourcePath: z => z.string().optional(),
        commitMessage: z => z.string().optional(),
        branch: z => z.string().optional(),
        createPR: z => z.boolean().optional(),
      },
      output: {
        pullRequestUrl: z => z.string().optional(),
      },
    },
    async handler(ctx) {
      const { host, owner, repo, sourcePath } = ctx.input;

      const commitMessage =
        ctx.input.commitMessage || 'infra: updated manifests via backstage';
      const branch = ctx.input.branch || 'main';
      const createPR = ctx.input.createPR || false;

      const allGiteaIntegrations = integrations.gitea.list();
      const integrationConfig = host
        ? integrations.gitea.byHost(host)
        : allGiteaIntegrations[0];
      const token = integrationConfig?.config.password;
      const username = integrationConfig?.config.username;
      const targetHost = integrationConfig?.config.host;
      const baseUrl = integrationConfig?.config.baseUrl;

      if (!token) throw new Error('Forgejo token missing.');
      if (!username) throw new Error('Forgejo username is missing');

      const targetCloneDir = `/tmp/backstage-gitops-${Date.now()}`;
      const repoUrl = `http://${username}:${token}@${targetHost}/${owner}/${repo}.git`;
      const workspaceSource = sourcePath
        ? path.resolve(ctx.workspacePath, sourcePath)
        : ctx.workspacePath;

      ctx.logger.info(`Cloning ${owner}/${repo} to ${targetCloneDir}...`);

      try {
        const git = simpleGit();

        await git.clone(repoUrl, targetCloneDir);
        const gitRepo = simpleGit(targetCloneDir);

        const targetBranch = createPR
          ? `backstage-update-${Date.now()}`
          : branch;

        if (createPR) {
          ctx.logger.info(
            `Creating and checking out new branch: ${targetBranch}`,
          );
          await gitRepo.checkoutLocalBranch(targetBranch);
        } else {
          ctx.logger.info(
            `Committing directly to base branch: ${targetBranch}`,
          );
          await gitRepo.checkout(targetBranch);
        }

        ctx.logger.info(`Copying rendered files into repo...`);
        await fs.copy(workspaceSource, targetCloneDir, { overwrite: true });

        await gitRepo.add('.');
        const status = await gitRepo.status();

        if (status.isClean()) {
          ctx.logger.info('No changes detected. Skipping commit.');
          return;
        }

        await gitRepo
          .addConfig('user.name', 'Scaffolder')
          .addConfig('user.email', 'no-reply@kamuridesu.com')
          .commit(commitMessage);
        await gitRepo.push('origin', targetBranch);
        ctx.logger.info(`Successfully pushed changes to ${targetBranch}`);

        if (createPR) {
          ctx.logger.info(`Opening Pull Request to ${branch}...`);
          const prResponse = await fetch(
            `${baseUrl}/api/v1/repos/${owner}/${repo}/pulls`,
            {
              method: 'POST',
              headers: {
                Authorization: `token ${token}`,
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                base: branch,
                head: targetBranch,
                title: commitMessage,
                body: 'Automated infrastructure update generated by Backstage Developer Portal.',
              }),
            },
          );

          if (!prResponse.ok) {
            throw new Error(
              `Forgejo PR creation failed: ${await prResponse.text()}`,
            );
          }

          const prData = (await prResponse.json()) as { html_url: string };
          ctx.logger.info(`PR Created Successfully: ${prData.html_url}`);
          ctx.output('pullRequestUrl', prData.html_url);
        }
      } finally {
        await fs.remove(targetCloneDir);
      }
    },
  });
}
