#!/bin/bash
set -e

echo "Starting Forgejo container"
docker compose up -d

echo "Waiting for Forgejo to start" 
while ! curl -s http://localhost:3000 >/dev/null; do
    sleep 2
done
sleep 3 

echo "Generating ssh keys"
mkdir -p keys
if [ ! -f keys/admin_key ]; then
  ssh-keygen -t ed25519 -f keys/admin_key -N "" -q
else
    chmod 600 keys/admin_key 
fi
if [ ! -f keys/user_key ]; then
  ssh-keygen -t ed25519 -f keys/user_key -N "" -q
else
    chmod 600 keys/user_key
fi

ADMIN_PUB=$(cat keys/admin_key.pub)
USER_PUB=$(cat keys/user_key.pub)

echo "Creating admin account"
docker exec -u git forgejo forgejo admin user create \
  --username forgejoadmin \
  --password "Admin123!" \
  --email admin@example.com \
  --admin

ADMIN_TOKEN=$(docker exec -u git forgejo forgejo admin user generate-access-token \
  --username forgejoadmin \
  --token-name setup \
  --raw | tr -d '\r')

echo "Creating normal user account"
docker exec -u git forgejo forgejo admin user create \
  --username testuser \
  --password "User123!" \
  --email testuser@example.com

USER_TOKEN=$(docker exec -u git forgejo forgejo admin user generate-access-token \
  --username testuser \
  --token-name setup \
  --raw | tr -d '\r')

echo "Creating test org"
curl -s -X POST "http://localhost:3000/api/v1/orgs" \
  -H "Authorization: token $ADMIN_TOKEN" \
  -H "Content-Type: application/json" \
  -d '{"username":"test-org", "description":"A test organization generated by the setup script."}' > /dev/null

echo "Uploading users keys"
curl -s -X POST "http://localhost:3000/api/v1/user/keys" \
  -H "Authorization: token $ADMIN_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{\"title\": \"admin-local-key\", \"key\": \"$ADMIN_PUB\"}" > /dev/null

curl -s -X POST "http://localhost:3000/api/v1/user/keys" \
  -H "Authorization: token $USER_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{\"title\": \"user-local-key\", \"key\": \"$USER_PUB\"}" > /dev/null

echo "Creating the ArgoCD repository in Forgejo"
curl -s -X POST "http://localhost:3000/api/v1/orgs/test-org/repos" \
  -H "Authorization: token $ADMIN_TOKEN" \
  -H "Content-Type: application/json" \
  -d '{"name":"argo-cd-repo", "description":"ArgoCD infrastructure repository", "private":false}' > /dev/null

echo "Generating ArgoCD values.yaml..."
cd ../argo-cd/repo

mkdir -p charts/argocd

KNOWN_HOSTS=$(ssh-keyscan -p 2222 localhost 2>/dev/null | grep -v "^#" | sed 's/^[^ ]*/[host.minikube.internal]:2222/' | awk '{print "        " $0}')
INDENTED_PRIVATE_KEY=$(awk '{print "          " $0}' ../../forgejo/keys/admin_key)

cat << EOF > charts/argocd/values.yaml
argo-cd:
  server:
    extraArgs:
      - --insecure

    ingress:
      enabled: true
      ingressClassName: haproxy
      hostname: argo.kamuridesu.com

  configs:
    ssh:
      knownHosts: |
${KNOWN_HOSTS}

    secret:
      createSecret: true

    credentialTemplates:
      forgejo-creds:
        url: ssh://git@host.minikube.internal:2222
        sshPrivateKey: |
${INDENTED_PRIVATE_KEY}

  rbac:
    policy.default: role:readonly
    policy.csv: |
      g, /ArgoCDAdmins, role:admin
EOF

echo "Pushing local files to the new repository"
rm -rf .git

git init -b main
git config user.name "forgejoadmin"
git config user.email "admin@example.com"
git add .
git commit -m "Initial commit from automated setup"

git remote add origin ssh://git@localhost:2222/test-org/argo-cd-repo.git

GIT_SSH_COMMAND="ssh -i ../../forgejo/keys/admin_key -p 2222 -o StrictHostKeyChecking=no" git push -u origin main

cd - > /dev/null

echo "Forgejo is available at: http://localhost:3000"
echo "Accounts Created:"
echo "- Admin Account  -> forgejoadmin:Admin123!"
echo "- Normal Account -> testuser:User123!"
echo ""
echo "ArgoCD Repository: http://localhost:3000/test-org/argo-cd-repo"
echo "ArgoCD Internal SSH URL configured as: ssh://git@host.minikube.internal:2222/test-org/argo-cd-repo.git"
